[google]
type = "service_account"
project_id = "api-drive-444401"
private_key_id = "8daaa6b1a8699d4d8aa02781bffdd080e7c6c9d8"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC93GMAoSMwpyI9
8jNrabp2OeMEUxhHaiRJjUDzqtXqxnXt9WtqRqYiJfy/wGkCfdwsU5BPcGSaFXO6
BGLsegl4z2mIWMPjCKr14DkxAszCRRxk5hRbnfCwbrmKIsO3dMrUuEi37z34sGJu
ZqomHOW1+Bpl4QjxOEhEuLJwsl/J3CjtgKaTKyG5nWx72Qff8PpJnzXerTYXstjQ
LUzlt0c2ylAIrYiG9I7iMF0jDcWCHgFrJJJd7BvVeWX9+CIgzOsSZHT3jQTSTyGs
1wSSVEsCnSLPEPC3QWB/1WXrMRYIq3a3+z7IhUWcz673KJHLfiMmEGq54ZH1ulU7
BxJ/8utrAgMBAAECggEAAloVCzXJIE9UYBe8ev5RINQgaPYjN7CWaNIsSvhuSZ1n
aj5fNBlSRzEDm60lVTJm7vuirtaRwHY3O/Iq9t/0zGomq1mMz6aqANK5Z/naEdFW
WTT1F+9xwwBpdvnC7+ZX+Yubhv/FMOv1GYYBtz17ZlDU+YxwlmsKkM4IPoIkfUp3
PU1BbwXo6spfLcEViKAMqGNK1K7fq7PIYmg32UA3gltzDgQeOQ24bC7rIxHL/Om2
dtkkpdrs3FdaEn9XPlvCEz5UTeU/kLfsEjdIvUNs5KVkDrElQWuBp0lZY8ghRV7/
9x73hslLzoxsNZRBJPGP7JK90LvuzfnFvC92WvLWBQKBgQDurffpWJy04XEWUndt
EL4vk5Y/2Ud6Ppx1Iu2/hHvAcFEmivngWTo5yQSaUQNoo5EcQBiVLEilE2KctsFp
Z1pfnCBBkNqgNYXbppb6o1dh9e0/zTfv8IsPrNRd2nidMPJJSOlIQeOTep4PN/5G
1G6pzrshKcUYmfQ7Bzj2MT1/pwKBgQDLo39B5azfuJnfc1mGgmNRHcvScs6TkPFc
1lCNY7wMgb4/k0zjJRLzAbqB0AL8oDVSumK1I+X79L0MSC/rHYNvqM2DsDS+flw7
1mrVXNSaZ0GqU2cu88ZtX/VO+XwRkeVtuWfYb8XuGKlRVSvaAzA0m5qJ5iwSKt9e
K6Y1McuOnQKBgQDduuorcjGqbCEVvqjJvpsgMbiMOjsH2rCYtUku+VHJ1c3dw5Ad
FmdcFV3cSlSjWgjNuNHdixU1ncunkLQfSm+PkMf6gSpJWU+wXZO25hWgoMm10t0b
X1igyEtFoVcZmMYMxNpLUUKs2GWL99WWUXU49R+s0FQU5bkZOT12oQnj0wKBgGWj
NvLm9X+8HWC/q+FM1tE3s/FXx+8zGqShexb2vnbnktMca/W7HVgYdsQv1C3OsI6X
5IhQYIt+vZSRuwj4dA+ZCuo9WjXxz4s2G6BecuaVvtqKQifXGCSjDkbakqgaT46S
SVhngTyzJl8nyXlIuhinyVwme7ydlVrlIlHOhrCpAoGAeH+5XHLBRIu17b7bbAKA
7e5i7qX45MktmPQKXHq7E0QiL0qG88utedwXf8lnpaDpOiVvfybJC5gjB2oAqYIA
mTv+q6tJTvA5xfpBaWWxAgor6pDDdIJtnXKIyb0AErBzT54x64jkEIKLkNMs6kiZ
inbvBd+8kw4A2dASaLxV4R4=
-----END PRIVATE KEY-----
"""
client_email = "salesperformance@api-drive-444401.iam.gserviceaccount.com"
client_id = "100257673425484120003"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/salesperformance%40api-drive-444401.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
